# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install development requirements
      run: |
          pip install -r requirements-dev.txt
          
    - name: Install testing requirements
      run: |
          pip install -r requirements-test.txt

    - name: Install requirements
      run: |
          pip install -r requirements.txt

    - name: Generate coverage report
      run: |
          pip install -e .
          PYTHONPATH="." pytest
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload coverage to Coveralls
      run: |
          COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      shell: bash

    - name: Build and Deploy Docs
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      if: ${{ github.event_name == 'push' && matrix.python_version == 3.8 && matrix.os == 'ubuntu-latest' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/html # The folder the action should deploy. This example folder is generated by Sphinx
        BUILD_SCRIPT: make html && touch docs/build/html/.nojekyll # The build script the action should run prior to deploying.

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/bandit-check@master
        with:
          path: 'metapandas'
      - name: Install mypy pre-requisites
        run: python3 -m pip install lxml mypy
      - name: mypy-check
        run: python3 -m mypy .
